# Generated by Django 4.0.2 on 2022-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heath_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_pulse', models.IntegerField()),
                ('calorie_burnage', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
